pipeline {
    agent any

    tools {
        maven 'maven-3'
        jdk 'jdk-17'
        // Remove the sonarQube line if it still causes issues
    }

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
        DOCKERHUB_USERNAME = 'giriprasad74'  // Set this directly to your Docker Hub username
        DOCKER_IMAGE = "${DOCKERHUB_USERNAME}/spotify-app:latest"
    }

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/giriNova74/DevOps-and-Cloud-Projects.git'
            }
        }

        stage('Compile') {
            steps {
                dir('project-2'){
                    sh "mvn compile"
                }
            }
        }

        stage('Test') {
            steps {
                dir('project-2'){
                    sh "mvn test"
                }
            }
        }

        stage('Sonar Analysis') {
            steps {
                dir('project-2'){
                withSonarQubeEnv('sonar-server') {
                    sh "$SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=Giri -Dsonar.projectKey=GiriKey -Dsonar.java.binaries=target"
                }
                }
            }
        }

        stage('Build') {
            steps {
                dir('project-2'){
                sh "mvn package"
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('project-2'){
                script {
                    // Building Docker Image
                    sh "docker build -t $DOCKER_IMAGE ."
                }
                }
            }
        }

        stage('Docker Push to DockerHub') {
            steps {
                dir('project-2'){
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-id', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                        echo "Docker Hub Username: ${DOCKERHUB_USERNAME}"  // Check the username
                        echo "Docker Image: ${DOCKER_IMAGE}"  // Check the image
                        sh "docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}"
                        sh "docker push $DOCKER_IMAGE"
                    }
                }
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                dir('project-2'){
                script {
                    // Stop any existing container with the same name
                    sh "docker stop spotify-app || true && docker rm spotify-app || true"
                    
                    // Running the container
                    sh "docker run -d --name spotify-app -p 5555:5555 $DOCKER_IMAGE"
                }
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace...'
            cleanWs()  // Clean up the workspace after the build
        }
    }
}